// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Regenerate(arg1:string):Promise<string>;

export function UpdateSettings(arg1:{[key: string]: any}):Promise<void>;
